version: "3.9"

services:
  api:
    build:
      context: ../api
      dockerfile: ../infra/docker/api.Dockerfile
    container_name: api
    restart: always

  front:
    build:
      context: ../front-office
      dockerfile: ../infra/docker/front-office.Dockerfile
    container_name: front
    restart: always

  back:
    build:
      context: ../back-office
      dockerfile: ../infra/docker/back-office.Dockerfile
    container_name: back
    restart: always

  nginx:
    image: nginx:alpine
    container_name: nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - front-dist:/usr/share/nginx/html/front
      - back-dist:/usr/share/nginx/html/back
    depends_on:
      - api
      - front
      - back

volumes:
  front-dist:
  back-dist:
