services:
  api:
    build:
      context: ../api
      dockerfile: ../infra/docker/api.Dockerfile
    container_name: api
    restart: always

  nginx:
    build:
      context: ../
      dockerfile: infra/docker/nginx.Dockerfile
    container_name: nginx
    ports:
      - "80:80"
    depends_on:
      - api
